FROM php:8.2-fpm

RUN echo "memory_limit = 256M" > /usr/local/etc/php/conf.d/memory-limit.ini

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www

# Prevent Symfony Flex from generating a project ID
ENV COMPOSER_ALLOW_SUPERUSER 1
