nelmio_api_doc:
    documentation:
        info:
            title: 'Steps Leaderboard API'
            description: 'This is the API documentation for the Steps Leaderboard application'
            version: 1.0.0
    areas:
        default:
            path_patterns: [ ^/api ]
